GET http://localhost:5166/games

###
GET http://localhost:5166/games/4

###
POST http://localhost:5166/games
Content-Type: application/json

{
  "name": "TeKa",
  "genreId": "1",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5166/games/4
Content-Type: application/json

{
  "name": "Dinasty Warriors",
  "genreId": "3",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

###
DELETE http://localhost:5166/games/5



